### ISSUE TITLE
when created a link-post, klicking on post ends in white window

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#36] opened 2017-12-23 13:54 UTC
The title describes the problem already. I use the app on mac.

**Comment by MihaiAlisie** [comment] 2017-12-26 08:25
Cheers for reporting the issue! We will look into this after 3rd January when we'll be back in our offices!

**Comment by SeverS** [comment] 2018-01-03 10:21
Hello!
Cannot reproduce this issue. Can you confirm that it\`s a link post? 
New Entry -> Link entry?
Can you give me the web address you used when creating the link entry?

**Comment by SeverS** [comment] 2018-01-03 15:45
Thanks for reporting! This issue is now fixed!

**Closed** 2018-01-18 10:35 UTC
Labels: bug, in progress
