### ISSUE TITLE
transform: adjust bar is not enough 

### ISSUE THREAD

**Issue by dirmansebastian** [AkashaProject/dapp#95] opened 2018-01-08 22:31 UTC
it's easier to insert a number in a text box

**Comment by bogdanbrezuica** [comment] 2018-01-09 09:49
I will close this as duplicate of [issue 60](https://github.com/AkashaProject/dapp/issues/60) 
Will be part of the next release.

Thanks

**Closed** 2018-01-09 09:49 UTC
